### PR TITLE
Fix Python client

### LINKED ISSUE #91: [bug] `list_agent_task*` endpoints on Python client are broken
**Package:** `agent-protocol-client` v1.0.2

The `list_agent_task*` endpoints on the `AgentApi` are broken:
* `list_agent_task_steps(task_id)` returns `['steps', 'pagination']`, because its `_response_types_map` declares the response as `List[str]`

* `list_agent_tasks_ids()` returns `['tasks', 'pagination']`, same issue as above

* `list_agent_task_artifacts(task_id)` raises a parsing error, see below:

The [`TaskArtifactsListResponse` spec](https://github.com/AI-Engineer-Foundation/agent-protocol/blob/ecbffe0b9e45bdd3ead76299af6d980a1132b32a/schemas/openapi.yml#L391-L402) prescribes a response format like `{ artifacts: Artifact[] }`. The client library [assumes](https://github.com/AI-Engineer-Foundation/agent-protocol/blob/ecbffe0b9e45bdd3ead76299af6d980a1132b32a/packages/client/python/agent_protocol_client/api/agent_api.py#L1086) it is just `Artifact[]`, which causes a parsing error on the response of compliant endpoints.

The error occurs here: https://github.com/AI-Engineer-Foundation/agent-protocol/blob/ecbffe0b9e45bdd3ead76299af6d980a1132b32a/packages/client/python/agent_protocol_client/api_client.py#L352-L355 and is caused by `... for sub_data in data` with `data` being an object like `{ 'artifacts': [...] }`: it calls `Artifact.parse_obj` on the string `artifacts`, which fails.

Resulting stack trace:
```
    artifacts = await api_instance.list_agent_task_artifacts(task_id=task_id)
/home/user/.local/lib/python3.11/site-packages/agent_protocol_client/api_client.py:268: in __call_api
    return_data = self.deserialize(response_data, response_type)
/home/user/.local/lib/python3.11/site-packages/agent_protocol_client/api_client.py:341: in deserialize
    return self.__deserialize(data, response_type)
/home/user/.local/lib/python3.11/site-packages/agent_protocol_client/api_client.py:357: in __deserialize
    return [self.__deserialize(sub_data, sub_kls) for sub_data in data]
/home/user/.local/lib/python3.11/site-packages/agent_protocol_client/api_client.py:357: in <listcomp>
    return [self.__deserialize(sub_data, sub_kls) for sub_data in data]
/home/user/.local/lib/python3.11/site-packages/agent_protocol_client/api_client.py:378: in __deserialize
    return self.__deserialize_model(data, klass)
/home/user/.local/lib/python3.11/site-packages/agent_protocol_client/api_client.py:840: in __deserialize_model
    return klass.from_dict(data)
/home/user/.local/lib/python3.11/site-packages/agent_protocol_client/models/artifact.py:68: in from_dict
    return Artifact.parse_obj(obj)
------------------------------------------------

>   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for Artifact
E   __root__
E     Artifact expected dict not str (type=type_error)

pydantic/main.py:525: ValidationError
```

### PR DESCRIPTION
**Pull request by Pwuts**
The Python client is currently broken (#91) and was built using an outdated generator. There are also some other issues (#92) with it, so here's a bundle of fixes. :)

- Fixes #91

## Changes

- Update generator from `python-nextgen` to `python-pydantic-v1`
- Fix line-endings in scripts/generate.sh
- Updated build script and config for Python client
- Built new Python client from schema
- Updated README

## Checklist

Please review and check the following items to ensure your pull request can be processed smoothly:

- [x] My code adheres to the project's coding standards and style guidelines.

- [x] I have tested my changes thoroughly, including unit tests where applicable.

- [x] I have updated the documentation to reflect any changes made in this pull request.

- [x] My branch is up-to-date with the latest changes from the main branch.

- [ ] I have received code review feedback and addressed any comments or concerns.

### CODE REVIEW

**Comment by Pwuts** [comment]
Testing is WIP

**Comment by Pwuts** [comment]
Update: tested, works

**Comment by ntindle** [comment]
LGTM

**Comment by jzanecook** [comment]
Thanks, Pwuts!

**Pull request merged**
