### PR TITLE
BugFix : Models : updated additional_input

### PR DESCRIPTION
**Pull request by vignesh14052002**
# Pull Request

This pull request contains a fix for v1 API endpoints for create task and execute step not accepting `additional_input` parameter , For more details refer this issue #82 

#### Issue : 
v1 API endpoints for create task `[POST]  /ap/v1/agent/tasks` and execute step `[POST]  /ap/v1/agent/tasks/{taskid}/steps` not accepting `additional_input` parameter

#### Reason : 
The pydantic models Task and Step has not configured `additional_input` property

#### Changes : 
Made `additional_input` property to type `Optional[Dict[str, Any]]` in python sdk

## Checklist

Please review and check the following items to ensure your pull request can be processed smoothly:

- [x] My code adheres to the project's coding standards and style guidelines.

- [x] I have tested my changes thoroughly, including unit tests where applicable.

- [ ] I have updated the documentation to reflect any changes made in this pull request.

- [x] My branch is up-to-date with the latest changes from the main branch.

- [ ] I have received code review feedback and addressed any comments or concerns.

## References, Fixes and Closes

- References #82

### CODE REVIEW

**Comment by hackgoofer** [comment]
@vignesh14052002 Can you join the meeting with us at 9:30am PST at the foundation discord? https://discord.com/invite/bJnNh666C3

Let's get this merged and resolved.

**Comment by hackgoofer** [comment]
@jzanecook to make sure that the test suite covers the case.

**Comment by jzanecook** [comment]
> @jzanecook to make sure that the test suite covers the case.

Checked the test suite, this is currently failing.

Here's the output:
image

**Comment by vignesh14052002** [comment]
@jzanecook how to run the test suite? i ran `packages\sdk\python\examples\minimal.py` to start the server and ran both `testing_suite/local_test.sh` and `testing_suite/test.sh` 

image

**Comment by vignesh14052002** [comment]
@jzanecook maybe it is due to js-sdk, i tried starting the js server, but not sure how to 
`examples/minimal.ts` is having some other issues 
image

 so reverted that change alone, can you run the test cases again

**Comment by vignesh14052002** [comment]
@hackgoofer missed the meeting , can you schedule another one , i will be available from 9:00AM IST to 6:00PM IST

**Comment by vignesh14052002** [comment]
> @vignesh14052002 Can you join the meeting with us at 9:30am PST at the foundation discord?

sure

**Comment by hackgoofer** [comment]
https://agentprotocol.ai/compliance here is how you test.

**Comment by vignesh14052002** [comment]
> https://agentprotocol.ai/compliance here is how you test.

@hackgoofer checked it , test cases passed

**Comment by vignesh14052002** [comment]
@hackgoofer @jzanecook Remainder! , seems you forgot to merge this PR

**Pull request merged**
